config/routes.rb
Rails.application.routes.draw do
  resources :image_files
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'messages#index'
  
  get 'show2', to: 'bokes#show2'
  
  get 'profiles', to: 'profiles#index'
  delete 'delete', to: 'bokes#destroy', as: 'delete'
  
  resources :messages, :bokes, :tiktokers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boke.rb
class Boke < ApplicationRecord
  validates :boke, presence: true, length: { maximum: 255 }
end

app/models/image_file.rb
class ImageFile < ApplicationRecord
  mount_uploader :file, FileUploader
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/tiktoker.rb
class Tiktoker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bokes_controller.rb
class BokesController < ApplicationController

  def index
    # sc1.pyで1ページ目スクレイピング開始
    
    @result = `python2 #{Rails.root}/app/controllers/sc1.py`

    @sc_url = @result.split('"').grep(/[jpg]/).select do |url|
                url.include?("jpg")
    end
    
    @img_url = []
    i=0
    @sc_url.each do |sc_url|
      @img_url[i] = "https:#{sc_url}"
      Boke.create(boke: '', image_url: @img_url[i] )
      i += 1
    end
    
    # sc1.pyで1ページ目スクレイピング終了
    # sc2.pyで2ページ目スクレイピング開始
    @result = `python2 #{Rails.root}/app/controllers/sc2.py`

    @sc_url = @result.split('"').grep(/[jpg]/).select do |url|
                url.include?("jpg")
    end
    
    i=10
    @sc_url.each do |sc_url|
      @img_url[i] = "https:#{sc_url}"
      Boke.create(boke: '', image_url: @img_url[i] )
      i += 1
    end
    # sc2.pyで2ページ目スクレイピング終了
    # sc3.pyで3ページ目スクレイピング開始
    @result = `python2 #{Rails.root}/app/controllers/sc3.py`

    @sc_url = @result.split('"').grep(/[jpg]/).select do |url|
                url.include?("jpg")
    end
    
    i=20
    @sc_url.each do |sc_url|
      @img_url[i] = "https:#{sc_url}"
      Boke.create(boke: '', image_url: @img_url[i] )
      i += 1
    end
    # sc3.pyで3ページ目スクレイピング終了
    
    
    
    @messages = Message.all
  end

  def show
    @params = params[:id]
    
    @message = Message.new
   
    @img_url = Boke.all.order(updated_at: "DESC")
  end
  
  def show2
    @params = params[:id]
    
    @random_image=Boke.where( 'id >= ?', rand(Boke.first.id..Boke.last.id) ).first.image_url
  end
  
  

  def new
    $new_boke_params = params[:img_url]
    
    @boke = Boke.new
  end

  def create
    @boke = Boke.new(boke_params)

    if @boke.save
      flash[:success] = 'ボケ が正常に投稿されました'
      @new_boke = Boke.last.update(image_url: $new_boke_params)
      redirect_to @boke
    else
      flash.now[:danger] = 'ボケ が投稿されませんでした'
      render :new
    end
  end

  def edit
    @params = params[:img_url]
    set_boke
  end

  def update
    @params = params[:id]
    set_boke

    if @boke.update(boke_params)
      flash[:success] = 'ボケ は正常に更新されました'
      redirect_to bokes_url
    else
      flash.now[:danger] = 'ボケ は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @params = params[:id]
    set_boke
    @boke.destroy

    flash[:success] = 'ボケ は正常に削除されました'
    redirect_to bokes_url
  end
  
   private
   
  def set_boke
    @boke = Boke.find(params[:id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def boke_params
    params.require(:boke).permit(:boke)
  end
  
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/image_files_controller.rb
class ImageFilesController < ApplicationController
  before_action :set_image_file, only: %i[ show edit update destroy ]

  # GET /image_files or /image_files.json
  def index
    @image_files = ImageFile.all
  end

  # GET /image_files/1 or /image_files/1.json
  def show
  end

  # GET /image_files/new
  def new
    @image_file = ImageFile.new
  end

  # GET /image_files/1/edit
  def edit
  end

  # POST /image_files or /image_files.json
  def create
    @image_file = ImageFile.new(image_file_params)

    respond_to do |format|
      if @image_file.save
        format.html { redirect_to image_file_url(@image_file), notice: "Image file was successfully created." }
        format.json { render :show, status: :created, location: @image_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_files/1 or /image_files/1.json
  def update
    respond_to do |format|
      if @image_file.update(image_file_params)
        format.html { redirect_to image_file_url(@image_file), notice: "Image file was successfully updated." }
        format.json { render :show, status: :ok, location: @image_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_files/1 or /image_files/1.json
  def destroy
    @image_file.destroy

    respond_to do |format|
      format.html { redirect_to image_files_url, notice: "Image file was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_file
      @image_file = ImageFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_file_params
      params.require(:image_file).permit(:title, :file, :content)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def show
    set_message
  end

  def new
    @message = Message.new
  end

  def create
     @message = Message.new(message_params)

    if @message.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message が投稿されませんでした'
      render :new
    end
  end

  def edit
    set_message
  end

  def update
    set_message

    if @message.update(message_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message は更新されませんでした'
      render :edit
    end
  end

  def destroy
    set_message
    @message.destroy

    flash[:success] = 'Message は正常に削除されました'
    redirect_to messages_url
  end
  
   private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end
end

app/controllers/tiktokers_controller.rb
class TiktokersController < ApplicationController
  def index
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bokes_helper.rb
module BokesHelper
end

app/helpers/image_files_helper.rb
module ImageFilesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tiktokers_helper.rb
module TiktokersHelper
end

app/views/bokes/index.html.erb
<%= stylesheet_link_tag "modal", :media => "all" %>
<%= stylesheet_link_tag "bokes_index", :media => "all" %>



<wrapper>
  <header class="top_index">
  <nav>
    <div class="top-left">
      <!--<p class="search"><%= image_tag 'search_white.png', size: '25x25' %></p>-->
      <!--<p>search</p>-->
    </div>
        
        
    <div class="top-center">  
      
    </div>
      
    <div class="top-right">
      <div id="modalOpen" class="menu">MENU</div>
    </div>
  </nav>
  </header>
  <section class="title">
    <h7>Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke</h7>
  </section>
  <section class="boke_theme">
  <h3>下の画像の中から、好きな画像を選んで、自由に「ボケ」てね！！</h3>
  <div>
    <% @img_url.each_with_index do |img_url, i| %>
    <figure class="card" style="width: 400px;">
    <figcaption>No. <%= i+1 %></figcaption>
    <p class="image card-img-top" alt="..."><%= image_tag img_url,width: '350px', height: '350px'  %></p>
    <span class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text"></p>
        <span class="btn btn-primary"><%= link_to 'ボケる',new_boke_path(img_url: img_url) %></span>
      </span>
    </figure>
    <% end %>
  </div>
</section>
<section class="boke_top">
  <div class="boke_index">
    <span class="bokes_show">今までのボケ一覧</span>
    <span id="bokes_show_button" class="btn btn-primary">
      <%= link_to '投稿されたボケを見る', boke_path(id: :id) %>
    </span>
  </div>
</section>

  <!--モーダルウィンドウ（MENUクリック時に呼び出されるHTML/CSS要素）-->
  <div id="easyModal" class="modal">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Great job 🎉</h2>
        <span class="modalClose">×</span>
      </div>
      <div class="modal-body">
        <p>You've just displayed this awesome Modal Window!</p>
        <p>Let's enjoy learning JavaScript ☺️</p>
        <a href="https://twitter.com/unounounouno31"><img class="twitter_icon" src="/assets/twitter_icon.jpeg" alt="twitter" width="30" height="30"></a>
        <a href="https://www.youtube.com/"><img class="youtube_icon" src="/assets/youtube.jpeg" alt="youtube" width="30" height="30"></a>
        <p></p>
        <ul>
          <nav>
            <li><%= link_to '会社概要', root_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'tiktoker紹介', tiktokers_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke', bokes_path, class: "text-decoration-none" %></li>
            <li><%= link_to '自己紹介', profiles_path, class: "text-decoration-none" %></li>
          </nav>
        </ul>
        <div>今までのサイト（別ページへ）　</div>
        <p><%= link_to '楽天の書籍検索APIを用いたブックレビューサイト myfavorites ', 'https://bookreview20220205.herokuapp.com/', class: "text-decoration-none" %></p>
      </div>
    </div>
  </div>
  <!--モーダルウィンドウ（終）-->
  </wrapper>
  
  <div class="under">事業内容</div>
  <div class="contents_bar">
    <span class="A"><%= link_to tiktokers_path do %><%= image_tag 'SAYA_up.jpeg', size: '450x350' %><% end %><p>tiktokerの動画コンテンツ販売、写真素材、グッズ作成、プロモーション活動、広告宣伝などのマーケティング活動</p></span>
    <span class="B"><%= link_to bokes_path do %><%= image_tag 'BOKE_up.png', size: '450x350' %><% end %><p>Webアプリケーションの作成　「Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke」</p></span>
    <span class="C"><%= link_to 'https://bookreview20220205.herokuapp.com/' do %><%= image_tag 'MYFAVORITES_up.jpeg', size: '450x350' %><% end %><p>Webアプリケーションの作成　「楽天の書籍検索APIを利用したブックレビューサイト myfavorites」</p></span>
  </div>
  
  <footer>
    <div>
      <span>お問合せ</span>
      <span>プライバシーポリシー</span>
      <span>サイトマップ</span>
    </div>
    <div>
      <div>© Copyright 2022 動画コンテンツ販売.</div>
      <div>動画コンテンツ販売 by FIT-Web Create. Powered by WordPress.</div>
    </div>
  </footer>
  
   <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    

app/views/bokes/show.html.erb
<%= stylesheet_link_tag "bokes_index", :media => "all" %>

 <section>
  <span class="btn btn-primary"><%= link_to 'ボケを選びに戻る', bokes_path(id: :id) %></span>
  <div>
    <% @img_url.each_with_index do |img_url, i| %>
    <figure class="card" style="width: 400px;">
    <figcaption>No. <%= i+1 %></figcaption>
    <p class="image card-img-top" alt="..."><%= image_tag img_url.image_url,width: '350px', height: '350px'  %></p>
    <span class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text"><%= img_url.boke  %></p>
        <span class="btn btn-primary"><%= link_to 'ボケる',edit_boke_path(id: img_url.id,img_url: img_url.image_url) %></span>
        <span class="btn btn-danger"><%= link_to 'ボケを消す',delete_path(id: img_url.id) %></span>
      </span>
    </figure>
    <% end %>
  </div>
</section>

app/views/bokes/show2.html.erb
<%= stylesheet_link_tag 'bokes_index', :media => 'all' %>

<wrapper>
  <h4>ランダム</h4>
  <section>
  <span class="btn btn-primary"><%= link_to 'ボケを選びに戻る', bokes_path(id: :id) %></span>
  <div>
    <figure class="card" style="width: 400px;">
    <figcaption>ランダムで表示</figcaption>
    <p class="image card-img-top" alt="..."><%= image_tag @random_image,width: '350px', height: '350px'  %></p>
    <span class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="./bokes/new" class="btn btn-primary">ボケる</a>
      </span>
    </figure>
  </div>
</section>

<footer>
<%= link_to '新規メッセージの投稿', new_message_path %>
</footer>
</wrapper>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %> のメッセージ編集ページ</h1>

<%= render 'form', message: @message %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/index.html.erb
<%= stylesheet_link_tag "index", :media => "all" %>
<%= stylesheet_link_tag "modal", :media => "all" %>

<wrapper>
<h1>To brighten<br> your<br> happiness</h1>
<header class="top_index">
  <nav>
    <div class="top-left">
      <!--<p class="search"><%= image_tag 'search_white.png', size: '25x25' %></p>-->
      <!--<p>search</p>-->
    </div>
        
        
    <div class="top-center">  
      
    </div>
      
    <div class="top-right">
      <div id="modalOpen" class="menu">MENU</div>
    </div>
  </nav>
</header>
<div class="under"><p>あなたの幸せを輝かせるために！</p></div>

<div class="above"><p>企業名</p></div>
<section class="our_name">
  <div>
    <h3>株式会社 to・you （トゥ・ユー）</h3>
    <p>私たちは、お客様のために、共に働く仲間のために、「笑顔」になれる何かを追求するための会社です。<br>
    具体的なサービスとしては、<br>
    1 インターネットサイトの構築（HTML/CSS/JavaScriptなどの言語で開発するフロントエンド系のサイト）<br>
    2 tiktokerの動画コンテンツ販売、写真素材、グッズ作成、プロモーション活動、広告宣伝などのマーケティング活動<br>
    3 アプリケーション開発(Ruby on railsによるデータベースを備えたサイト構築 ＋ API / Python　などによる、ユーザーを楽しませるWebアプリケーションの開発)<br>
    を主軸に、その時々で、お客様の要望に応じたシステム開発により、収益を得ています。
    </p>
  </div>
</section>
<div class="under"></div>


<div class="above"><p>企業情報</p></div>
<section class="our_business">
  <div>
    <p>企業理念</p>
    <p class="idea"><span>お客様のために、共に働く仲間のために、「笑顔」を追求することです。<br>
    周囲の人が笑顔になれるシステムを提案したり、お客様の要望にお応えできる開発を
    進めていけるような人材が、to_youには必要です。</span></p>
  </div>
  <div　class="our_total">
      <p>会社概要</p>
<table class="table table-bordered col-sm-12">
  <tbody>
    <tr>
      <th scope="row col-sm-2">名称</th>
      <td scope="col-sm-3">株式会社 to_you</td>
    </tr>
    <tr>
      <th scope="row">代表</th>
      <td>to_you</td>
    </tr>
    <tr>
      <th scope="row">代表電話番号</th>
      <td>06-0606-0606</td>
    </tr>
    <tr>
      <th scope="row">FAX番号</th>
      <td>06-0707-0707</td>
    </tr>
    <tr>
      <th scope="row">資本金</th>
      <td>500万</td>
    </tr>
     <tr>
      <th scope="row">所在地（本社）</th>
      <td>〒555-0041 大阪府大阪市西淀川区中島２丁目２−４５(仮)</td>
    </tr>
  </tbody>
</table>
  </div>
</section>

<div class="above"><p>アクセス</p></p></div>
<section class="map">
  <div><%= image_tag 'アクセス2.jpg', size: '500x350' %><p>JR御幣島駅→本拠所在地</p></div>
  <div><%= image_tag 'アクセス1.png', size: '500x350' %><p>なんば線　福駅→本拠所在地</p></div>
</section>
<div class="under">事業内容</div>
  <div class="contents_bar">
    <span class="A"><%= link_to tiktokers_path do %><%= image_tag 'SAYA_up.jpeg', size: '450x350' %><% end %><p>tiktokerの動画コンテンツ販売、写真素材、グッズ作成、プロモーション活動、広告宣伝などのマーケティング活動</p></span>
    <span class="B"><%= link_to bokes_path do %><%= image_tag 'BOKE_up.png', size: '450x350' %><% end %><p>Webアプリケーションの作成　「Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke」</p></span>
    <span class="C"><%= link_to 'https://bookreview20220205.herokuapp.com/' do %><%= image_tag 'MYFAVORITES_up.jpeg', size: '450x350' %><% end %><p>Webアプリケーションの作成　「楽天の書籍検索APIを利用したブックレビューサイト myfavorites」</p></span>
  </div>
  
<div class="text_slider"><p>Welcome to my page, 「タイトル（考え中）」!!オーダーメイドいけます！！</p></div>

  <!--モーダルウィンドウ（MENUクリック時に呼び出されるHTML/CSS要素）-->
  <div id="easyModal" class="modal">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Great job 🎉</h2>
        <span class="modalClose">×</span>
      </div>
      <div class="modal-body">
        <p>You've just displayed this awesome Modal Window!</p>
        <p>Let's enjoy learning JavaScript ☺️</p>
        <a href="https://twitter.com/unounounouno31"><img class="twitter_icon" src="/assets/twitter_icon.jpeg" alt="twitter" width="30" height="30"></a>
        <a href="https://www.youtube.com/"><img class="youtube_icon" src="/assets/youtube.jpeg" alt="youtube" width="30" height="30"></a>
        <p></p>
        <ul>
          <nav>
            <li><%= link_to '会社概要', root_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'tiktoker紹介', tiktokers_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke', bokes_path, class: "text-decoration-none" %></li>
            <li><%= link_to '自己紹介', profiles_path, class: "text-decoration-none" %></li>
          </nav>
        </ul>
        <div>今までのサイト（別ページへ）　</div>
        <p><%= link_to '楽天の書籍検索APIを用いたブックレビューサイト myfavorites ', 'https://bookreview20220205.herokuapp.com/', class: "text-decoration-none" %></p>
      </div>
    </div>
  </div>
  <!--モーダルウィンドウ（終）-->
</wrapper>
 <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render 'form', message: @message %>

<%= link_to '一覧に戻る', messages_path %>

app/views/messages/show.html.erb
<h1>id: <%= @message.id %> のメッセージ詳細ページ</h1>

<p><%= @message.content %></p>

<%= link_to '一覧に戻る', messages_path %>
<%= link_to 'このメッセージを編集する', edit_message_path(@message) %>
<%= link_to 'このメッセージを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/tiktokers/index.html.erb
<%= stylesheet_link_tag "t_index", :media => "all" %>
<%= stylesheet_link_tag "index", :media => "all" %>
<%= stylesheet_link_tag "modal", :media => "all" %>

<header class="tiktoker_index">
  <nav>
    <div class="top-left">
      <!--<p class="search"><%= image_tag 'search_white.png', size: '25x25' %></p>-->
      <!--<p>search</p>-->
    </div>
        
        
    <div class="top-center">  
      
    </div>
      
    <div class="top-right">
      <div id="modalOpen" class="menu">MENU</div>
    </div>
  </nav>
</header>

  <div class="image_slider">
    <div class="image1"><%= image_tag 'SAYA.jpg', size: '350x300' %><p>click here!!</p><span>さや</span></div>
    <div class="image2"><%= image_tag 'YUKA.jpg', size: '350x300' %><p>click here!!</p><span>ゆか</span></div>
    <div class="image3"><%= image_tag 'sora1.jpg', size: '350x300' %><p>click here!!</p><span>そら</span></div>
    <div class="image4"><%= image_tag 'はしも。1.jpg', size: '350x300' %><p>click here!!</p><span>はしも。</span></div>
    <div class="image5"><%= image_tag 'SAYA.jpg', size: '350x300' %><p>click here!!</p><span>さや</span></div>
    <div class="image6"><%= image_tag 'YUKA.jpg', size: '350x300' %><p>click here!!</p><span>ゆか</span></div>
    <div class="image7"><%= image_tag 'sora1.jpg', size: '350x300' %><p>click here!!</p><span>そら</span></div>
    <div class="image8"><%= image_tag 'はしも。1.jpg', size: '350x300' %><p>click here!!</p><span>はしも。</span></div>
    <div class="image9"><%= image_tag 'SAYA.jpg', size: '350x300' %><p>click here!!</p><span>さや</span></div>
    <div class="image10"><%= image_tag 'YUKA.jpg', size: '350x300' %><p>click here!!</p><span>ゆか</span></div>
    <div class="image11"><%= image_tag 'sora1.jpg', size: '350x300' %><p>click here!!</p><span>そら</span></div>
    <div class="image12"><%= image_tag 'はしも。1.jpg', size: '350x300' %><p>click here!!</p><span>はしも。</span></div>
  </div>


<div class="above"><p>tiktoker 一覧</p></div>
  <div class="menber_activity">
      <div class="menber_activity_image1">
      <h2> 1 さや </h2>
      <div><span><%= image_tag 'SAYA.jpg', size: '350x300' %></span><p>天真爛漫のtiktoker。心踊る世界を夢見て、tiktokerへと転身。「私の道を決めるのは、質でも量でもない、心のトキメキ具合だ！（ドン）」</p></div>
      </div>
    <div class="menber_activity_image2">
      <h2> 2 ゆか </h2>
      <div><span><%= image_tag 'YUKA.jpg', size: '350x300' %></span><p>誠心誠意のtiktoker。見たものを和ませ、唯一無二の感情を生み出す。彼女のモットーは、「雨のち晴れ」</p></div>
    </div>
    <div class="menber_activity_image3">
      <h2> 3 そら </h2>
      <div><span><%= image_tag 'sora1.jpg', size: '350x300' %></span><p>理路整然のtiktoker。論理的に思考し、最適解を常に導くことを生きがいにしている。「詰将棋をしているときに浮かぶ棋譜」をあるあるネタにしてくる。</p></div>
    </div>
    <div class="menber_activity_image4">
      <h2> 4 はしも。 </h2>
      <div><span><%= image_tag 'はしも。1.jpg', size: '350x300' %></span><p>四苦八苦のtiktoker。常にネタを考えているが、ボツになることもしばしば。彼が唯一市民権を得た特技は、ネタがなくて煮詰まった時に出る「困り顔」</p></div>
    </div>
  </div>
  <div class="under"></div>
  
    <section class="profile">
    <div class="information">
      <p>tiktoker さや</p>
    </div>
  
    <!--モーダルウィンドウ（MENUクリック時に呼び出されるHTML/CSS要素）-->
  <div id="easyModal" class="modal">
    <div class="modal-content">
      <div class="modal-header">
        <h2>Great job 🎉</h2>
        <span class="modalClose">×</span>
      </div>
      <div class="modal-body">
        <p>You've just displayed this awesome Modal Window!</p>
        <p>Let's enjoy learning JavaScript ☺️</p>
        <a href="https://twitter.com/unounounouno31"><img class="twitter_icon" src="/assets/twitter_icon.jpeg" alt="twitter" width="30" height="30"></a>
        <a href="https://www.youtube.com/"><img class="youtube_icon" src="/assets/youtube.jpeg" alt="youtube" width="30" height="30"></a>
        <p></p>
        <ul>
          <nav>
            <li><%= link_to '会社概要', root_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'tiktoker紹介', tiktokers_path, class: "text-decoration-none" %></li>
            <li><%= link_to 'Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke', bokes_path, class: "text-decoration-none" %></li>
            <li><%= link_to '自己紹介', profiles_path, class: "text-decoration-none" %></li>
          </nav>
        </ul>
        <div>今までのサイト（別ページへ）　</div>
        <p><%= link_to '楽天の書籍検索APIを用いたブックレビューサイト myfavorites ', 'https://bookreview20220205.herokuapp.com/', class: "text-decoration-none" %></p>
      </div>
    </div>
  </div>
  <!--モーダルウィンドウ（終）-->
  <div class="under">事業内容</div>
  <div class="contents_bar">
    <span class="A"><%= link_to tiktokers_path do %><%= image_tag 'SAYA_up.jpeg', size: '450x350' %><% end %><p>tiktokerの動画コンテンツ販売、写真素材、グッズ作成、プロモーション活動、広告宣伝などのマーケティング活動</p></span>
    <span class="B"><%= link_to bokes_path do %><%= image_tag 'BOKE_up.png', size: '450x350' %><% end %><p>Webアプリケーションの作成　「Pythonによるボケて！のサイトから大喜利のお題をWebスクレイピングした大喜利保存サイト boke」</p></span>
    <span class="C"><%= link_to 'https://bookreview20220205.herokuapp.com/' do %><%= image_tag 'MYFAVORITES_up.jpeg', size: '450x350' %><% end %><p>Webアプリケーションの作成　「楽天の書籍検索APIを利用したブックレビューサイト myfavorites」</p></span>
  </div>
  
  <footer>
  <div>
    <span>お問合せ</span>
    <span>プライバシーポリシー</span>
    <span>サイトマップ</span>
  </div>
  <div>
    <div>© Copyright 2022 動画コンテンツ販売.</div>
    <div>動画コンテンツ販売 by FIT-Web Create. Powered by WordPress.</div>
  </div>
</footer>
  
      <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
 